# LYCEUM OF THE PHILIPPINES UNIVERSITY – LAGUNA
### College of Business and Accountancy

---

# BDAT05 — Preliminary Assessment
## Part 2A · Practical Demonstration — **Notebook D**

**Fundamentals of Predictive Analytics** · Term 1, AY 2026–2027 · Saturday, 12 September 2026

| | |
|---|---|
| **Duration** | **60 minutes** |
| **Dataset** | *Lavandera Ko* — a laundry chain you have never seen |
| **Conditions** | Open notes — including your own P2/P3 notebooks and code. **No AI of any kind.** |
| **After this** | Part 2B: you present THIS notebook to me, and defend it |

### The rules of the hour

1. **Five sections, in order.** Each ends with an **EVIDENCE** cell (print the number) and a **READING** sentence (what the number means). A number without a sentence is half an answer.
2. **Reuse your own code freely.** That is not cheating; that is why you built it.
3. **Nothing changes silently.** Every row you remove or repair gets counted, in print.
4. Stuck 10 minutes? Write what you *would* do in the reading cell and move on — method earns marks even when code fights back.

---

*Course Facilitator: Jerald B. Bongalos*

## Setup — run once, at the start

In [ ]:
STUDENT_NAME = "Eliah Therrien Sanchez"        # <-- your full name
TRACK = "P5"               # <-- P4, P5, P6 or P7

# ---------------------------------------------------------------- do not edit below
from datetime import datetime
START_TIME = datetime.now()
NOTEBOOK_CODE = "D"
print(f"Notebook {NOTEBOOK_CODE} — {STUDENT_NAME or 'NAME NOT ENTERED'} ({TRACK or '?'})")
print(f"Started at {START_TIME:%H:%M} — you have 60 minutes")

Notebook D — Eliah Therrien Sanchez (P5)
Started at 07:42 — you have 60 minutes

## Load the data

Paste the three FILE_IDs from the board, then run.

In [11]:
# ============================================================
# LOAD 3 DATA FILES FROM GOOGLE DRIVE
# ============================================================

# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')


# 2. Import libraries
import pandas as pd
import os


# 3. Set the Google Drive folder path
folder_path = "/content/drive/MyDrive/Prelim Materials 05"


# 4. Check that the folder exists
if not os.path.exists(folder_path):
    print("ERROR: Folder not found.")
    print("Please check that 'Prelim Materials 05' is inside My Drive.")
else:
    print("Folder found!")
    print()


# 5. Display the files inside the folder
print("Files in Google Drive folder:")
print("--------------------------------")

files = os.listdir(folder_path)

for file in files:
    print(file)


# 6. Load the 3 CSV files
orders_path = os.path.join(folder_path, "lavandera_orders.csv")
branches_path = os.path.join(folder_path, "lavandera_branches.csv")
calendar_path = os.path.join(folder_path, "lavandera_calendar.csv")

orders = pd.read_csv(orders_path)
branches = pd.read_csv(branches_path)
calendar = pd.read_csv(calendar_path)


# 7. Confirm that the files were loaded
print()
print("================================================")
print("FILES LOADED SUCCESSFULLY")
print("================================================")

print("Orders:", orders.shape)
print("Branches:", branches.shape)
print("Calendar:", calendar.shape)


# 8. Display the first 5 rows of each file
print()
print("========== ORDERS ==========")
display(orders.head())

print()
print("========== BRANCHES ==========")
display(branches.head())

print()
print("========== CALENDAR ==========")
display(calendar.head())

Mounted at /content/drive
Folder found!

Files in Google Drive folder:
--------------------------------
lavandera_orders.csv
lavandera_branches.csv
lavandera_calendar.csv

================================================
FILES LOADED SUCCESSFULLY
================================================
Orders: (8000, 7)
Branches: (6, 4)
Calendar: (608, 7)

========== ORDERS ==========

  OrderID        Date BranchID  ServiceType KiloWeight  Amount PaymentMethod
0  O11092  2025-07-24      L01  Wash & Fold       12.9  462.68         GCash
1  O15755  2026-01-22      L02    Dry Clean        3.6  450.11          Cash
2  O11565  2026-03-09      L04      Ironing        6.6  284.15         GCash
3  O14663  2025-12-18      L02  Wash & Fold        6.5  239.14         GCash
4  O12111  2026-06-08      L03     Beddings        8.4  558.21          Cash

========== BRANCHES ==========

  BranchID  BranchName             City  OpenedDate
0      L01     Calamba     Calamba City  2020-02-10
1      L02     Cabuyao     Cabuyao City  2021-06-01
2      L03       Binan       Binan City  2021-11-15
3      L04  Santa Rosa  Santa Rosa City  2022-08-20
4      L05   San Pedro   San Pedro City  2023-04-03

========== CALENDAR ==========

         Date  Year  MonthNo MonthName YearMonth    DayName  DayType
0  2025-01-01  2025        1   January   2025-01  Wednesday  Weekday
1  2025-01-02  2025        1   January   2025-01   Thursday  Weekday
2  2025-01-03  2025        1   January   2025-01     Friday  Weekday
3  2025-01-04  2025        1   January   2025-01   Saturday  Weekend
4  2025-01-05  2025        1   January   2025-01     Sunday  Weekend

---

# §1 · The handshake  *(≈8 minutes)*

Run the full handshake on `orders`: `info()`, `head()`, missing counts. Then answer in the READING cell: **row count, column count, and every column whose dtype is wrong for what it holds** — with what each wrong type would silently break.

In [12]:
# §1 — your handshake code
# ============================================================
# §1 · THE HANDSHAKE — ORDERS
# info(), head(), and missing-value counts
# ============================================================

print("=" * 60)
print("ORDERS — FULL HANDSHAKE")
print("=" * 60)


# 1. INFO()
print("\n§1A · INFO()")
print("-" * 60)
orders.info()


# 2. HEAD()
print("\n§1B · HEAD() — FIRST 5 ROWS")
print("-" * 60)
display(orders.head())


# 3. MISSING COUNTS
print("\n§1C · MISSING VALUES BY COLUMN")
print("-" * 60)

missing_counts = orders.isna().sum()

display(missing_counts.to_frame(name="Missing Count"))


# 4. SUMMARY
print("\n§1D · QUICK SUMMARY")
print("-" * 60)

print("Row count:", orders.shape[0])
print("Column count:", orders.shape[1])
print("Total missing values:", orders.isna().sum().sum())

print("\nColumns with missing values:")
display(missing_counts[missing_counts > 0])

============================================================
ORDERS — FULL HANDSHAKE
============================================================

§1A · INFO()
------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        8000 non-null   object
 1   Date           7980 non-null   object
 2   BranchID       8000 non-null   object
 3   ServiceType    8000 non-null   object
 4   KiloWeight     8000 non-null   object
 5   Amount         8000 non-null   float64
 6   PaymentMethod  8000 non-null   object
dtypes: float64(1), object(6)
memory usage: 437.6+ KB

§1B · HEAD() — FIRST 5 ROWS
------------------------------------------------------------

  OrderID        Date BranchID  ServiceType KiloWeight  Amount PaymentMethod
0  O11092  2025-07-24      L01  Wash & Fold       12.9  462.68         GCash
1  O15755  2026-01-22      L02    Dry Clean        3.6  450.11          Cash
2  O11565  2026-03-09      L04      Ironing        6.6  284.15         GCash
3  O14663  2025-12-18      L02  Wash & Fold        6.5  239.14         GCash
4  O12111  2026-06-08      L03     Beddings        8.4  558.21          Cash

§1C · MISSING VALUES BY COLUMN
------------------------------------------------------------

               Missing Count
OrderID                    0
Date                      20
BranchID                   0
ServiceType                0
KiloWeight                 0
Amount                     0
PaymentMethod              0

§1D · QUICK SUMMARY
------------------------------------------------------------
Row count: 8000
Column count: 7
Total missing values: 20

Columns with missing values:

Date    20
dtype: int64

In [15]:
# §1 EVIDENCE — automatically calculate and print

# Total number of rows
S1_ROWS = len(orders)

# Check data types
print("Column data types:")
print(orders.dtypes)

# Identify columns with potentially wrong/unexpected data types
# Date is expected to be object at this stage because it is loaded as text.
# We will clean Date separately in §2.

S1_WRONG_DTYPES = ""

print()
print("Rows:", S1_ROWS, "| Wrong dtypes:", S1_WRONG_DTYPES)

Column data types:
OrderID                  object
Date             datetime64[ns]
BranchID                 object
ServiceType              object
KiloWeight               object
Amount                  float64
PaymentMethod            object
dtype: object

Rows: 8000 | Wrong dtypes:

**§1 READING** *(edit this cell — one or two sentences: what did the handshake warn you about?)*
---------------

The handshake warned me that there were 20 missing values in Date.
> ...

---

# §2 · Cleaning — Make the dates real  *(≈12 minutes)*

`Date` loaded as text. **Parse it to a real datetime**, count how many rows fail or are missing, and decide what happens to them — printing the row count before and after your decision. Nothing changes silently.

In [13]:
# ============================================================
# §2 · CLEANING — DATE
# Parse Date from text to real datetime
# Count missing and failed values
# ============================================================

print("=" * 60)
print("DATE CLEANING")
print("=" * 60)

# 1. Show Date as originally loaded
print("\n§2A · DATE AS LOADED")
print("-" * 60)

print("Data type before cleaning:", orders["Date"].dtype)
display(orders[["Date"]].head(10))


# 2. Count values that were already missing
missing_before = orders["Date"].isna().sum()


# 3. Parse Date into real datetime
orders["Date"] = pd.to_datetime(
    orders["Date"],
    errors="coerce"
)


# 4. Count missing values after parsing
missing_after = orders["Date"].isna().sum()


# 5. Count rows that FAILED parsing
failed_count = missing_after - missing_before


# 6. Show results
print("\n§2B · DATE PARSING RESULTS")
print("-" * 60)

print("Missing dates before parsing:", missing_before)
print("Failed/invalid dates:", failed_count)
print("Missing dates after parsing:", missing_after)
print("Data type after cleaning:", orders["Date"].dtype)


# 7. Show rows that failed parsing
if failed_count > 0:
    print("\n§2C · ROWS THAT FAILED DATE PARSING")
    print("-" * 60)
    display(orders[orders["Date"].isna()])
else:
    print("\n§2C · NO INVALID DATES FOUND")

============================================================
DATE CLEANING
============================================================

§2A · DATE AS LOADED
------------------------------------------------------------
Data type before cleaning: object

         Date
0  2025-07-24
1  2026-01-22
2  2026-03-09
3  2025-12-18
4  2026-06-08
5  2026-05-01
6  2025-07-14
7  2026-06-28
8  2026-06-14
9  2026-05-03

§2B · DATE PARSING RESULTS
------------------------------------------------------------
Missing dates before parsing: 20
Failed/invalid dates: 0
Missing dates after parsing: 20
Data type after cleaning: datetime64[ns]

§2C · NO INVALID DATES FOUND

In [14]:
# §2 EVIDENCE — automatically calculate and print

rows_before = len(orders)

# Count missing dates before parsing
missing_before = orders["Date"].isna().sum()

# Parse Date
orders["Date"] = pd.to_datetime(orders["Date"], errors="coerce")

# Count missing after parsing
missing_after = orders["Date"].isna().sum()

# Rows that failed parsing
unparseable = missing_after - missing_before

S2_EVIDENCE = (
    f"Unparseable/missing dates: {unparseable} unparseable, "
    f"{missing_before} originally missing · "
    f"rows before: {rows_before} · after: {len(orders)}"
)

print(S2_EVIDENCE)

Unparseable/missing dates: 0 unparseable, 20 originally missing · rows before: 8000 · after: 8000

**§2 READING** *(edit — the decision and its reason, as a cleaning-log line: issue → decision → why)*
----

I would remove the 20 dates missing because they cannot be assigned to a payment month and it has no use for a Date.
> ...

---

# §3 · The grain — Build the payment-month grain  *(≈12 minutes)*

Using your parsed dates: build a table where **one row = one payment method in one month**, with the **count of orders**. **Print the row count** of your grain table.

In [17]:
# ============================================================
# §3 · PAYMENT-MONTH GRAIN
# ============================================================

# Show all column names
print("Columns in orders:")
for i, col in enumerate(orders.columns):
    print(i, repr(col))


# Find the payment-method column automatically
payment_candidates = [
    col for col in orders.columns
    if "payment" in col.lower()
]

print("\nPossible payment columns:")
print(payment_candidates)

Columns in orders:
0 'OrderID'
1 'Date'
2 'BranchID'
3 'ServiceType'
4 'KiloWeight'
5 'Amount'
6 'PaymentMethod'
7 'Payment_Month'

Possible payment columns:
['PaymentMethod', 'Payment_Month']

In [19]:
# ============================================================
# §3 · PAYMENT-MONTH GRAIN + EVIDENCE
# ============================================================

# Identify the payment column
payment_candidates = [
    col for col in orders.columns
    if "payment" in col.lower()
]

payment_col = payment_candidates[0]

# Create month from parsed Date
orders["Payment_Month"] = orders["Date"].dt.to_period("M")

# Build payment-month grain
payment_month = (
    orders
    .dropna(subset=["Date", payment_col])
    .groupby(["Payment_Month", payment_col])
    .size()
    .reset_index(name="Order_Count")
    .sort_values(["Payment_Month", payment_col])
    .reset_index(drop=True)
)

# Show grain
print("PAYMENT-MONTH GRAIN")
print("-" * 50)
display(payment_month.head(20))

# §3 EVIDENCE
S3_GRAIN_ROWS = len(payment_month)

print("\n§3 EVIDENCE")
print("-" * 50)
print("Grain rows:", S3_GRAIN_ROWS)

PAYMENT-MONTH GRAIN
--------------------------------------------------

   Payment_Month PaymentMethod  Order_Count
0        2025-01          Cash          220
1        2025-01         GCash          143
2        2025-01          Maya           38
3        2025-02          Cash          196
4        2025-02         GCash          101
5        2025-02          Maya           39
6        2025-03          Cash          217
7        2025-03         GCash          136
8        2025-03          Maya           38
9        2025-04          Cash          212
10       2025-04         GCash          133
11       2025-04          Maya           40
12       2025-05          Cash          244
13       2025-05         GCash          154
14       2025-05          Maya           51
15       2025-06          Cash          200
16       2025-06         GCash          161
17       2025-06          Maya           62
18       2025-07          Cash          205
19       2025-07         GCash          128

§3 EVIDENCE
--------------------------------------------------
Grain rows: 60

**§3 READING** *(edit — state the grain in row language, and whether the count is what the calendar and the business would predict)*
----

The grain rows are 60, which is what the calendar and business would predict. Example: 20 months multipled by 3 payment methods = 60.
> ...

---

# §4 · Diagnostic — Diagnostic — the column that lies about its type  *(≈14 minutes)*

One numeric-in-meaning column is stored as text. **Find it, explain WHY it happened** (show the evidence), recover it, and report how many values caused it and the recovered maximum.

In [20]:
# ============================================================
# §4 · DIAGNOSTIC — FIND NUMERIC-IN-MEANING COLUMN STORED AS TEXT
# ============================================================

print("=" * 60)
print("NUMERIC-IN-MEANING COLUMNS STORED AS TEXT")
print("=" * 60)

for col in orders.columns:
    # Only inspect text/object columns
    if orders[col].dtype == "object":

        # Try converting the column to numeric
        converted = pd.to_numeric(orders[col], errors="coerce")

        # Count non-missing original values
        original_nonmissing = orders[col].notna().sum()

        # Count values successfully converted to numbers
        numeric_values = converted.notna().sum()

        # Calculate percentage that can be interpreted as numeric
        if original_nonmissing > 0:
            numeric_pct = numeric_values / original_nonmissing * 100
        else:
            numeric_pct = 0

        print(
            f"{col}: {numeric_values}/{original_nonmissing} "
            f"values numeric ({numeric_pct:.1f}%)"
        )

============================================================
NUMERIC-IN-MEANING COLUMNS STORED AS TEXT
============================================================
OrderID: 0/8000 values numeric (0.0%)
BranchID: 0/8000 values numeric (0.0%)
ServiceType: 0/8000 values numeric (0.0%)
KiloWeight: 7985/8000 values numeric (99.8%)
PaymentMethod: 0/8000 values numeric (0.0%)

In [21]:
# ============================================================
# §4 EVIDENCE — automatically identify and report the culprit
# ============================================================

# Find object/text columns that are numeric in meaning
numeric_text_columns = []

for col in orders.columns:
    if orders[col].dtype == "object":

        converted = pd.to_numeric(orders[col], errors="coerce")

        original_nonmissing = orders[col].notna().sum()
        numeric_values = converted.notna().sum()

        if original_nonmissing > 0:
            numeric_pct = numeric_values / original_nonmissing * 100

            if numeric_pct >= 95:
                numeric_text_columns.append(col)


# Select the suspected culprit
culprit = numeric_text_columns[0]

# Get the numeric version
culprit_numeric = pd.to_numeric(
    orders[culprit],
    errors="coerce"
)

# Get a few example culprit values
culprit_values = orders[culprit].dropna().head(5).tolist()

# Find the recovered maximum
recovered_max = culprit_numeric.max()


# Build evidence statement
S4_EVIDENCE = (
    f"Column: {culprit} "
    f"· culprit values: {culprit_values} "
    f"· recovered max: {recovered_max}"
)

print(S4_EVIDENCE)

Column: KiloWeight · culprit values: ['12.9', '3.6', '6.6', '6.5', '8.4'] · recovered max: 29.2

**§4 READING** *(edit — what you found, and what it would have silently done to an analysis that missed it)*
----

There are 5 culprit values as seen on the evidence in the KiloWeight column. Plus, KiloWeight was stored as text even though it should be a numeric data type.
> ...

---

# §5 · Judgment — Judgment — the 2,000-kilo order  *(≈14 minutes)*

Compute the IQR fences on your recovered `KiloWeight`. Report how many rows sit beyond the upper fence — then look at your **single heaviest order** and RULE on it: **KEEP / FLAG / DROP**, with the reason a manager would accept. Numbers first, verdict second.

In [22]:
# ============================================================
# §5 · JUDGEMENT — 2000-KILO ORDER / KiloWeight OUTLIER CHECK
# ============================================================

# 1. Recover KiloWeight as numeric
orders["KiloWeight_numeric"] = pd.to_numeric(
    orders["KiloWeight"],
    errors="coerce"
)

# 2. Calculate Q1 and Q3
Q1 = orders["KiloWeight_numeric"].quantile(0.25)
Q3 = orders["KiloWeight_numeric"].quantile(0.75)

# 3. Calculate IQR
IQR = Q3 - Q1

# 4. Calculate IQR fences
lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

# 5. Find rows beyond the upper fence
upper_outliers = orders[
    orders["KiloWeight_numeric"] > upper_fence
]

# 6. Find the single heaviest order
heaviest_index = orders["KiloWeight_numeric"].idxmax()
heaviest_order = orders.loc[[heaviest_index]]


# ============================================================
# RESULTS
# ============================================================

print("=" * 60)
print("KILOWEIGHT IQR DIAGNOSTIC")
print("=" * 60)

print(f"Q1: {Q1}")
print(f"Q3: {Q3}")
print(f"IQR: {IQR}")
print(f"Lower fence: {lower_fence}")
print(f"Upper fence: {upper_fence}")

print()
print("Rows beyond upper fence:", len(upper_outliers))

print()
print("=" * 60)
print("SINGLE HEAVIEST ORDER")
print("=" * 60)

display(heaviest_order)

============================================================
KILOWEIGHT IQR DIAGNOSTIC
============================================================
Q1: 6.1
Q3: 10.2
IQR: 4.1
Lower fence: -0.04999999999999982
Upper fence: 16.349999999999998

Rows beyond upper fence: 173

============================================================
SINGLE HEAVIEST ORDER
============================================================

,OrderID,Date,BranchID,ServiceType,KiloWeight,Amount,PaymentMethod,Payment_Month,KiloWeight_numeric
4228,O17187,2025-07-30,L06,Wash & Fold,29.2,1002.45,Maya,2025-07,29.2

**§5 VERDICT** *(edit this cell — your numbers, then your ruling and its defense. This is the section you will be asked about first in Part 2B.)*
----

The single heaviest order was OrderID O17187.

My ruling: Flag

My reason: The 29.2kg order is above the upper fence of 16.349. The reason why I did not drop the order is because it could be multiple customers in a record.
> ...

## Finish — run before you save

In [23]:
END_TIME = datetime.now()
print("=" * 52)
print(f"BDAT05 PRELIM — PART 2A · NOTEBOOK {NOTEBOOK_CODE}")
print("=" * 52)
print(f"Name     : {STUDENT_NAME}")
print(f"Track    : {TRACK}")
print(f"Duration : {(END_TIME - START_TIME).seconds // 60} minutes of 60")
print("-" * 52)
print("Save as: BDAT05_Prelim_Part2A_" + NOTEBOOK_CODE + "_" +
      (STUDENT_NAME.split()[-1].upper() if STUDENT_NAME else "SURNAME") + ".ipynb")
print("Upload to your prelim-assessment folder. Then we talk.")

====================================================
BDAT05 PRELIM — PART 2A · NOTEBOOK D
====================================================
Name     : Eliah Therrien Sanchez
Track    : P5
Duration : 54 minutes of 60
----------------------------------------------------
Save as: BDAT05_Prelim_Part2A_D_SANCHEZ.ipynb
Upload to your prelim-assessment folder. Then we talk.

https://chatgpt.com/share/6aa50fb7-bfdc-83ec-88b4-a2a52284e998