In [ ]:
import pandas as pd
sales = pd.read_csv("<path>/sales.csv") # adapt path & filename
sales.info()
sales.head(10)

FileNotFoundError: [Errno 2] No such file or directory: '<path>/sales.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

sales = pd.read_csv('/content/drive/MyDrive/sales_transactions.csv')

sales.info()
sales.head(10)
def validate(df, name):
    print(f"=== {name} ===")
    print("rows:", len(df))
    print("dtypes:\n", df.dtypes)                      # 1 type
    print("missing:\n", df.isna().sum())               # 2 completeness
    print("duplicate ids:", df["<id_col>"].duplicated().sum())   # 3 uniqueness
    print("negative amounts:", (df["<amount_col>"] < 0).sum())   # 4 range
    # 5 referential: keys in this table missing from the parent table
    # orphans = set(df["<key>"]) - set(parent["<key>"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SaleID         10589 non-null  int64
 1   Date           10577 non-null  object
 2   BranchID       10589 non-null  object
 3   ProductID      10589 non-null  object
 4   CustomerID     5814 non-null   object
 5   Quantity       10589 non-null  int64
 6   UnitPrice      10589 non-null  int64
 7   Amount         10589 non-null  float64
 8   PaymentMethod  10589 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 744.7+ KB

In [ ]:
sales.groupby("BranchID")["Amount"].sum().sort_values(ascending=False)

BranchID
B01     607298.18
B02     505149.08
B03     421895.03
B05     408700.00
B04     352604.76
B06     214558.75
b01       2750.00
B03       2325.00
B-05      1400.00
B-02      1300.00
b04        975.00
B06        955.00
Name: Amount, dtype: float64

In [ ]:
import pandas as pd

kape = pd.ExcelFile('/content/drive/MyDrive/KapeTayo_IntegratedCase.xlsx')

kape.sheet_names

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/KapeTayo_IntegratedCase.xlsx'

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'Getting started.pdf',
 'TLE-9-ASYNCHRONOUS-Act.1-2-1.gdoc',
 'Classroom',
 '1629633229219156860454331285585.jpg',
 '10- St. Thomas math',
 'IMG_20210914_193638.jpg',
 "Share 'Analytica-English..pptx'",
 'IMG20211108110324.jpg',
 'IMG20211108110329.jpg',
 "Share 'english-exam.docx'",
 'IMG20211209133455.jpg',
 'received_641715386880100.jpeg',
 'received_573871337272691.jpeg',
 'received_909236176659252.jpeg',
 'IMG20211014182542.jpg',
 'received_560278878566043.jpeg',
 'received_233570202086657.jpeg',
 'IMG20211014183611.jpg',
 'IMG20211014182559.jpg',
 'received_210008124568150.jpeg',
 'IMG20210822195158.jpg',
 'received_2925803334399416.jpeg',
 'IMG20211014114951.jpg',
 'received_4596442627102007.jpeg',
 'received_425021105872600.jpeg',
 'video-1645366609.mp4',
 'Lopez, Val Anthonne C.',
 'Anthonne lopez.heic',
 '8EE30A07-F912-4785-9915-569149743709.jpeg',
 'RESPIRATORY ',
 'Group 2 - interview.odt',
 'Mil g4',
 'Untitled document (1).gdoc',
 'IMG_4364.jpeg',
 'IMG_4375.jpeg',
 'att.4Mhy-QwW6gpingzK6nJ9zZrkqvhXOATZ1f0pq1zzKm8.png.jpeg',
 'att.Z5wfOIaaUx24nGrlpUFY3OSmu3lULRpezRmHfiWPeos.png.jpeg',
 'att.-laE319iTKLDtcN8DuHKpIpdZQJMkW4OufJ5kS6N8ks.jpeg',
 'att.azfDOrHHS4p_BkbbB-6Bm5hHTmAhEBEgdXO3sWOAZ58.jpeg',
 'att.q8bOh0R3AA7yneFRKrSA43Vaqkf1BLN0w0WwpK3oSy4.jpeg',
 '53ee34d1b8e5195e43ad9f238a0f0311.jpeg',
 'att.f5dXlDFCDOf_pHiGxcAxLUXRCy-2Abx_Am1hauTfIQY.jpeg',
 'att.rCWPhrK0N62Zjs-NEY_CqxCNzDmyCQ0NnhLVTf_N0C4.jpeg',
 'att.3ladynPawOZJv2NE5-B9Oocb3wBVZ3Hz03UPabflWCA.jpeg',
 'IMG_6805.MOV',
 'att.DlzuXVpxYUH4e0bNzJdkC7uxscEpKUqlzY_l3PWL1Co.jpeg',
 'att.Ks34A-KAne-iBbyi8YIj3u-JudWPLq8gdcDc2Ptgj7Y.png.jpeg',
 'att.e5zBZv354hIjB17qESKZ0v3wFVe_8fqv4uaeDh6dauo.png.jpeg',
 'LOPEZ_LETTER OF INTENT.gdoc',
 'Gecow pdf.gdoc',
 'Untitled document.gdoc',
 'att._NsUaC2GU2YDDOk_GNmUysTLlsxazQ6ItM2vAYd758w.png.jpeg',
 'att.CN9gp0QDDT7GkkE9_pXfnogfH0osWzWCDA8sdelBi_U (1).jpeg',
 'att.CN9gp0QDDT7GkkE9_pXfnogfH0osWzWCDA8sdelBi_U.jpeg',
 'sales_transactions.csv']

In [ ]:
branches = pd.read_csv('/content/drive/MyDrive/branches.csv')

branches.info()
branches.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   BranchID     6 non-null      object
 1   BranchName   6 non-null      object
 2   City         6 non-null      object
 3   Province     6 non-null      object
 4   OpenedDate   6 non-null      object
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  10 non-null     object
 11  Unnamed: 11  11 non-null     object
 12  Unnamed: 12  1 non-null      object
 13  Unnamed: 13  0 non-null      float64
 14  Unnamed: 14  0 non-null      float64
 15  Unnamed: 15  8 non-null      object
 16  Unnamed: 16  8 non-null      object
 17  Unnamed: 17  8 non-null      object
dtypes: float64(7), object(11)
memory usage: 2.2+ KB

,BranchID,BranchName,City,Province,OpenedDate,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,B01,Calamba,Calamba City,Laguna,3/1/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B02,Santa Rosa,Santa Rosa City,Laguna,7/15/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B03,Binan,Binan City,Laguna,1/20/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B04,San Pablo,San Pablo City,Laguna,5/10/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BRANCH,AVG PRICE,AVG CUPS/DAY
4,B05,Los Banos,Los Banos,Laguna,8/1/2023,NaN,NaN,NaN,NaN,NaN,DAY,SALES,NaN,NaN,NaN,SANP,90,220

In [ ]:
merged = pd.merge(sales, branches, on="BranchID", how="inner")

len(sales), len(merged)

(10589, 10549)

In [ ]:
orphan_branches = sales.loc[~sales["BranchID"].isin(branches["BranchID"]), "BranchID"]

orphan_branches.value_counts()

BranchID
b01     12
B03      7
B-02     7
B-05     5
b04      5
B06      4
Name: count, dtype: int64

In [ ]:
def validate(df, name):
    print(f"=== {name} ===")
    print("rows:", len(df))
    print("dtypes:\n", df.dtypes)
    print("missing:\n", df.isna().sum())
    print("duplicate ids:", df["SaleID"].duplicated().sum())
    print("negative amounts:", (df["Amount"] < 0).sum())

In [ ]:
validate(sales, "sales")

=== sales ===
rows: 10589
dtypes:
 SaleID             int64
Date              object
BranchID          object
ProductID         object
CustomerID        object
Quantity           int64
UnitPrice          int64
Amount           float64
PaymentMethod     object
dtype: object
missing:
 SaleID              0
Date               12
BranchID            0
ProductID           0
CustomerID       4775
Quantity            0
UnitPrice           0
Amount              0
PaymentMethod       0
dtype: int64
duplicate ids: 23
negative amounts: 0

In [ ]:
sales["Date"] = pd.to_datetime(sales["Date"], errors="coerce")

sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SaleID         10589 non-null  int64
 1   Date           10577 non-null  datetime64[ns]
 2   BranchID       10589 non-null  object
 3   ProductID      10589 non-null  object
 4   CustomerID     5814 non-null   object
 5   Quantity       10589 non-null  int64
 6   UnitPrice      10589 non-null  int64
 7   Amount         10589 non-null  float64
 8   PaymentMethod  10589 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 744.7+ KB

In [ ]:
sales["Year"] = sales["Date"].dt.year
sales["Month"] = sales["Date"].dt.month

sales[["Date", "Year", "Month"]].head(10)

        Date    Year  Month
0 2026-05-01  2026.0    5.0
1 2026-01-18  2026.0    1.0
2 2025-05-11  2025.0    5.0
3 2025-08-14  2025.0    8.0
4 2025-08-09  2025.0    8.0
5 2025-11-12  2025.0   11.0
6 2025-08-20  2025.0    8.0
7 2026-05-22  2026.0    5.0
8 2026-05-02  2026.0    5.0
9 2025-10-13  2025.0   10.0

In [ ]:
branch_month_revenue = (
    sales.groupby(["BranchID", "Year", "Month"])["Amount"]
    .sum()
    .reset_index()
)

branch_month_revenue.head(10)

  BranchID    Year  Month  Amount
0     B-02  2025.0    3.0   110.0
1     B-02  2025.0    6.0   175.0
2     B-02  2025.0    8.0   110.0
3     B-02  2025.0    9.0   380.0
4     B-02  2026.0    1.0   190.0
5     B-02  2026.0    5.0   180.0
6     B-02  2026.0    6.0   155.0
7     B-05  2025.0   10.0   525.0
8     B-05  2025.0   12.0   165.0
9     B-05  2026.0    1.0   350.0

In [ ]:
len(branch_month_revenue)

143

In [ ]:
validate(branch_month_revenue, "branch_month_revenue")

=== branch_month_revenue ===
rows: 143
dtypes:
 BranchID     object
Year        float64
Month       float64
Amount      float64
dtype: object
missing:
 BranchID    0
Year        0
Month       0
Amount      0
dtype: int64

KeyError: '<id_col>'

In [ ]:
print("=== branch_month_revenue ===")
print("rows:", len(branch_month_revenue))
print("\nmissing:")
print(branch_month_revenue.isna().sum())
print("\nduplicate branch-year-month combinations:",
      branch_month_revenue.duplicated(
          subset=["BranchID", "Year", "Month"]
      ).sum())
print("\nnegative amounts:",
      (branch_month_revenue["Amount"] < 0).sum())

=== branch_month_revenue ===
rows: 143

missing:
BranchID    0
Year        0
Month       0
Amount      0
dtype: int64

duplicate branch-year-month combinations: 0

negative amounts: 0

This slice uses sales transaction data containing BranchID, Date, and Amount to calculate total revenue by branch and month. It does not identify individual customers because the results are aggregated at the branch-month level and do not include customer names or CustomerID. Aggregating the data helps protect individual customer information because individual transactions are not shown in the final output. The analysis is intended only for business analysis and reporting purposes.

In [22]:
# P4 — Create cleaned branch-month revenue dataset

import pandas as pd

# Load the original files
sales = pd.read_csv('/content/drive/MyDrive/sales_transactions.csv')
branches = pd.read_csv('/content/drive/MyDrive/branches.csv')

# -----------------------------
# 1. Clean BranchID formatting
# -----------------------------
sales["BranchID"] = (
    sales["BranchID"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace("-", "", regex=False)
)

branches["BranchID"] = (
    branches["BranchID"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace("-", "", regex=False)
)

# Keep only branch records with a BranchID
branches_clean = branches.dropna(subset=["BranchID"]).copy()

# Remove duplicate branch IDs if any
branches_clean = branches_clean.drop_duplicates(subset=["BranchID"])

# -----------------------------
# 2. Convert Date
# -----------------------------
sales["Date"] = pd.to_datetime(sales["Date"], errors="coerce")

# -----------------------------
# 3. Create Year and Month
# -----------------------------
sales["Year"] = sales["Date"].dt.year
sales["Month"] = sales["Date"].dt.month

# -----------------------------
# 4. Merge Sales + Branches
# -----------------------------
merged_p4 = pd.merge(
    sales,
    branches_clean[["BranchID", "BranchName", "City", "Province"]],
    on="BranchID",
    how="inner"
)

# -----------------------------
# 5. Create branch-month revenue
# -----------------------------
branch_month_revenue = (
    merged_p4
    .dropna(subset=["Year", "Month"])
    .groupby(
        ["BranchID", "BranchName", "City", "Province", "Year", "Month"],
        as_index=False
    )["Amount"]
    .sum()
)

# -----------------------------
# 6. Display result
# -----------------------------
print("Rows:", len(branch_month_revenue))
print("Branches:", branch_month_revenue["BranchID"].nunique())

branch_month_revenue.head(10)

Rows: 108
Branches: 6

  BranchID BranchName          City Province    Year  Month    Amount
0      B01    Calamba  Calamba City   Laguna  2025.0    1.0  32340.00
1      B01    Calamba  Calamba City   Laguna  2025.0    2.0  27375.00
2      B01    Calamba  Calamba City   Laguna  2025.0    3.0  32480.00
3      B01    Calamba  Calamba City   Laguna  2025.0    4.0  31215.00
4      B01    Calamba  Calamba City   Laguna  2025.0    5.0  33165.00
5      B01    Calamba  Calamba City   Laguna  2025.0    6.0  30325.00
6      B01    Calamba  Calamba City   Laguna  2025.0    7.0  28815.00
7      B01    Calamba  Calamba City   Laguna  2025.0    8.0  40306.66
8      B01    Calamba  Calamba City   Laguna  2025.0    9.0  32560.00
9      B01    Calamba  Calamba City   Laguna  2025.0   10.0  28055.00

In [23]:
# Save the cleaned P4 dataset to Google Drive

output_path = '/content/drive/MyDrive/P4_branch_month_revenue_cleaned.csv'

branch_month_revenue.to_csv(output_path, index=False)

print("Cleaned dataset saved to:")
print(output_path)

Cleaned dataset saved to:
/content/drive/MyDrive/P4_branch_month_revenue_cleaned.csv

In [24]:
import os

print(os.path.exists('/content/drive/MyDrive/P4_branch_month_revenue_cleaned.csv'))

True